version: '3.4'

services:
  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: Services/Payment.API/Dockerfile
    ports:
      - 8001:8001
    
  payment.gateway:
    image: ${DOCKER_REGISTRY-}paymentgateway
    build:
      context: .
      dockerfile: Gateways/Payment.Gateway/Dockerfile
    ports:
      - 8000:8000